### ISSUE TITLE
Why are you using MySQL?

### ISSUE THREAD

**Issue by eabase** [domGitDev/ence-connectors#1]
Hi, 
Look like a cool project, but why are you using MySQL? 
It seem to be complete overkill for this type of extremely simple data.

Even SQLite3 would be better, far simpler, possibly faster and much smaller memory print.

**Comment by domGitDev** [comment]
Actually also have InfluxDB integrated just need to compile and publish. The data insert intto MySQL is only for later use. Data should be used via kafka.

**Comment by domGitDev** [comment]
Have look at this pool implementation I did for mysql and influxdb. It gave me very good db performance for real-time data.
- https://github.com/domGitDev/sqlpoolcpp
- https://github.com/domGitDev/influxpoolcpp

**Comment by domGitDev** [comment]
@eabase  I think the best is to remove database dependencies from connectors so users can have choices. 
Will only provide any example how to do it (similar to local order book management).

**Comment by eabase** [comment]
@domGitDev  
> the best is to remove database dependencies from connectors

Great idea, but then it's important to also have instructions on how to add them.
